---
slug: Continuous-Delivery
filename: Continuous-Delivery
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2017
uuid: 59b8392f-44ff-4722-97ec-102b3f7402ef
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
